version: "3.8"

services:
  checkin-app:
    build: .
    container_name: checkin
    ports:
      - "5000:5000"
    environment:
      TELEGRAM_TOKEN: "${TELEGRAM_TOKEN}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID}"
    volumes:
      - ./ponto.db:/app/ponto.db
    restart: always
